import FormCreatePost from "@/src/components/forms/FormCreatePost";
import MyAppshell from "@/src/components/layouts/AppShell";
import Posts from "@/src/components/posts/Posts";
import { Container, Space } from "@mantine/core";
import Head from "next/head";

export default function Home() {
    const angka:number = 5;
    console.log(!!angka)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyAppshell>
        <Container>
          <FormCreatePost />
          <Space h="xl" />
          <Posts />
        </Container>
      </MyAppshell>
    </>
  );
}